version: 2

project_name: kzgit

before:
  hooks:
    - go mod tidy

builds:
  - id: kzgit
    main: .
    binary: kzgit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/karoza/kz-git-user/cmd.version={{ .Version }}
      - -X github.com/karoza/kz-git-user/cmd.commit={{ .ShortCommit }}
      - -X github.com/karoza/kz-git-user/cmd.date={{ .Date }}

archives:
  - id: kzgit
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: karozadev
    name: KzGitUser
  prerelease: auto
